### PR TITLE
url fix (previous article / next article)

### PR DESCRIPTION
**Pull request by khyoz**
correction-slug
url with slug was not ok for previous and next article links.

### CODE REVIEW

**Comment by khyoz** [comment]
wrong destination, sorry, it was for develop not master

**Comment by baijunyao** [comment]
This is a bug fix, not a breaking change, you can modify the code and PR on the master branch.

**Comment by khyoz** [comment]
arf, ok I reopen it then, sorry again

**Comment by khyoz** [comment]
sorry ! I make mistakes with git, still not familiar with all the commands, this takes the social branch code as well

**Comment by baijunyao** [comment]
It doesn't matter.

**Pull request closed without merging**
