### PR TITLE
Article slug

### PR DESCRIPTION
**Pull request by khyoz**
Article slug for SEO

### CODE REVIEW

**Comment by khyoz** [comment]
not an expert on git with PR yet, can you tell me if that is what you asked by "Can you change the PR target to the develop branch? I will add an upgrade command, thank you."

**Comment by baijunyao** [comment]
You don't need to open a new PR, you can change the `base` to `develop` and `compare` to your `khyoz:article-slug`   in #44 .
WX20190519-143030@2x

**Comment by khyoz** [comment]
ok, I tried and now I have a message 
'A pull request already exists for base branch 'develop' and head branch 'article-slug''
so I believe I need to close this one ?

**Comment by baijunyao** [comment]
Yes

**Pull request merged**
